mongodb:
  db: settlment
  host: localhost
  port: 27017

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: settlement
      username: settlement-user
      password: 21405apple
      applicaitionname: settlement-api

debug:
  false

server:
  port:
    8080