mongodb:
  db: settlment
  host: localhost
  port: 27017

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/settlement
      database: settlement
      username: settlement-user
      password: 21405apple
      applicaitionname: settlement-api
